language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  fast_finish: true
  # allow_failures:
  # - julia: nightly

addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-0

before_script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/ChristianKurz/REPLGamesBase.jl.git")); Pkg.build("REPLGamesBase")'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/FielddocTables.jl")); Pkg.build("FielddocTables")'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/Cellular.jl.git")); Pkg.build("Cellular")'

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      # disable global before_script in order not to install Compose twice
      before_script:
      script:
        - |
          julia --color=yes --project=docs/ -e'
            using Pkg
            Pkg.add(PackageSpec(name="Compose", rev="master"))
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")
          '
          after_success: skip
